Update xvs icon
VenusProtocol/venus-protocol-interface pull request #213
Opened 2022-03-22 16:00 UTC by baomastr

2022-03-22 16:56 UTC, therealemjy commented
There's an issue with the `viewbox` of the new SVG icon, which makes it look smaller than the one of the VAI token:
<img width="223" alt="Screenshot 2022-03-22 at 16 55 37" src="https://user-images.githubusercontent.com/44675210/159533834-e508f025-76bb-4aec-81e6-a915116cab90.png">

<img width="222" alt="Screenshot 2022-03-22 at 16 55 40" src="https://user-images.githubusercontent.com/44675210/159533808-6b597451-4823-40d1-b169-a0ed6faafb1d.png">

2022-03-22 17:49 UTC, baomastr commented
> There's an issue with the `viewbox` of the new SVG icon, which makes it look smaller than the one of the VAI token:

fixed with reimport token icon

2022-03-22 19:12 UTC, therealemjy commented on src/assets/img/venus_active.svg
>  </svg>
This file isn't used, it should be removed

2022-03-22 19:18 UTC, coreyar approved these changes

2022-03-22 19:21 UTC, therealemjy requested changes
There's a few files that need to be removed since they aren't used anymore:

src/assets/img/venus_32.png
src/assets/img/coins/xvs.png

2022-03-23 07:28 UTC, baomastr commented
> There's a few files that need to be removed since they aren't used anymore:

done

2022-03-23 07:31 UTC, baomastr commented
@therealemjy 
Designer asked to hold the PR until the approve from business, so I added WIP status

2022-03-23 22:03 UTC, coreyar commented
> @therealemjy Designer asked to hold the PR until the business team approved changes, so I added WIP status

Let's use Draft PRs instead of the PR title to note that a PR is still in progress

2022-03-24 17:47 UTC, therealemjy approved these changes

2022-03-31 13:28 UTC, merged