Feature: add select component
VenusProtocol/venus-protocol-interface pull request #414
Opened 2022-05-05 10:02 UTC by baomastr

2022-05-05 16:07 UTC, therealemjy requested changes
Hey,
Sorry but this doesn't match the designs:
<img width="347" alt="Screen Shot 2022-05-05 at 17 06 38" src="https://user-images.githubusercontent.com/44675210/166965603-91c26b72-e358-4b58-841c-19a2e9dd530a.png">
Designs:
<img width="573" alt="Screen Shot 2022-05-05 at 17 06 32" src="https://user-images.githubusercontent.com/44675210/166965631-9e1917b4-d1ec-41f9-9ba7-6314c886749d.png">

2022-05-08 21:01 UTC, therealemjy commented
Much better 👍

2022-05-08 21:07 UTC, therealemjy reviewed
It displays a title on mobile:
<img width="375" alt="Screen Shot 2022-05-08 at 22 05 57" src="https://user-images.githubusercontent.com/44675210/167315796-b23c37e1-5f53-42fa-a457-64030dc622bf.png">

Since we don't have mobile designs for this component I think it's fine to use MUI's default one, but let's remove the title.

2022-05-08 21:07 UTC, therealemjy commented on src/components/v2/Select/index.tsx
> +  const [selectedValue, setSelectedValue] = React.useState(DEFAULT_OPTION.value);
The state and its modifier function should be passed through props, as we'll always need to use the state from the parent component that renders it

2022-05-08 21:07 UTC, therealemjy commented on src/components/v2/Select/index.tsx
> +};
I'd remove that to make it more flexible (not all selects will have a default "All" option).

2022-05-08 21:07 UTC, therealemjy commented on src/components/v2/Select/index.tsx
> +export const Select = ({ className, options }: ISelectProps) => {
Please use `React.FC` to type it like we do with other components

2022-05-09 12:30 UTC, coreyar commented on src/components/v2/Select/index.stories.tsx
> +      default: '#1F2028',
Ideally this value comes from the enum of options we have set `Primary` `Paper` `White`. They are set in `.storybook/preview.js` if not we can grab them from the Palette constant

2022-05-09 18:51 UTC, baomastr commented
@therealemjy 

> Since we don't have mobile designs for this component I think it's fine to use MUI's default one, but let's remove the title.

here are mobile designs:

![image](https://user-images.githubusercontent.com/14794071/167477405-0846e007-7022-4210-85d0-d16ba0648ba5.png)

2022-05-16 12:19 UTC, therealemjy commented
Ah right, nice 👍
Looks good to me.

2022-05-16 12:20 UTC, therealemjy approved these changes

2022-05-16 12:23 UTC, therealemjy requested changes

2022-05-16 12:23 UTC, therealemjy commented on src/components/v2/Select/index.tsx
> +      ...(isSmDown ? mobileStyles : {}),
Actually, I just saw that.

We want to move away from using JS for responsiveness: let's use CSS directly here (you can render both mobile and desktop instances of the component and choose which one to render based on the screen size using CSS directly).
Also, please don't copy and paste the whole code: you can make it so only the style prop differs from one version to the other.

2022-05-16 13:36 UTC, therealemjy commented
Actually never mind, we can't use CSS only here because of how MUI renders the dropdown menu.
Looks all good to me then 👍

2022-05-16 13:36 UTC, therealemjy approved these changes

2022-05-16 13:37 UTC, merged