[VEN-1132] Market table now has sorting options when in mobile view (master)
VenusProtocol/venus-protocol-interface pull request #979
Opened 2023-03-07 05:59 UTC by gleiser-oliveira

## Jira ticket(s)

VEN-1132

## Changes

- Mobile viewport now lets the user is sort markets by: total supply, supply APY, liquidity, total borrow and borrow APY.

2023-03-08 11:31 UTC, therealemjy requested changes
It works great on mobile but you'll need to hide the select on higher resolutions:
<img width="350" alt="Screen Shot 2023-03-08 at 11 28 18" src="https://user-images.githubusercontent.com/44675210/223701997-25be9f5a-a52d-4e30-ba83-8c62862bd5fc.png">

2023-03-08 11:31 UTC, therealemjy commented on src/components/Table/TableCards.tsx
> +  console.log(order);
An oversight from coding hehe

2023-03-08 22:19 UTC, gleiser-oliveira commented on src/components/Table/TableCards.tsx
> +  console.log(order);
🙈

2023-03-08 22:21 UTC, gleiser-oliveira commented
> 

Indeed, thanks for catching that! I was under the false impression it was hidden, but it was there all the way down the list. Fixed.

2023-03-09 17:28 UTC, therealemjy approved these changes

2023-03-10 13:27 UTC, merged